In [4]:
#Revision of Numpy Library..


#importing of numpy 
import numpy as np

#creating arrays using numpy.
array1 = np.array([1,2,3,4,5,6,7,8,9,10])
array1


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
#creating multidimentional array using numpy
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
#adding null values using numpy.

array3 = np.array([[1,2,np.nan],[4,np.nan,6],[7,8,9]])
array3

array([[ 1.,  2., nan],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.]])

In [7]:
#how to create a matrix using numpy.
matrix1 = np.matrix(array2)
print("Matrix 1 =",matrix1)

arr = ([6,4,3],[8,4,8],[6,3,8])

matrix2 = np.matrix(arr)
print("\nMatrix 2=",matrix2)

Matrix 1 = [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2= [[6 4 3]
 [8 4 8]
 [6 3 8]]


In [8]:
#perform different matrix operations using numpy

#addition of matrix
addition = np.add(matrix1,matrix2)
print("The additon of two matrix is:",addition)

The additon of two matrix is: [[ 7  6  6]
 [12  9 14]
 [13 11 17]]


In [9]:
#subtraction of matrix
subtraction = np.subtract(matrix1,matrix2)
print("\nThe subtraction of two matrix is:",subtraction)



The subtraction of two matrix is: [[-5 -2  0]
 [-4  1 -2]
 [ 1  5  1]]


In [10]:
#transpose of matrix
print("\nTranspose of martix1 is:",np.transpose(matrix1))
print("\nTranspose of matrix2 is:",np.transpose(matrix2))


Transpose of martix1 is: [[1 4 7]
 [2 5 8]
 [3 6 9]]

Transpose of matrix2 is: [[6 8 6]
 [4 4 3]
 [3 8 8]]


In [11]:
#product of matrix
print("\nProduct of martix is:",np.dot(matrix1,matrix2))


Product of martix is: [[ 40  21  43]
 [100  54 100]
 [160  87 157]]


In [12]:
#determinant of matrix
print("\nDeterminant of martix1 is:",np.linalg.det(matrix1))
print("\nDeterminant of matrix2 is:",np.linalg.det(matrix2))


Determinant of martix1 is: 6.66133814775094e-16

Determinant of matrix2 is: -15.999999999999998


In [13]:
#inverse of matrix 
print("\nInverse of martix1 is:",np.linalg.inv(matrix1))
print("\nInverse of matrix2 is:",np.linalg.inv(matrix2))


Inverse of martix1 is: [[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]

Inverse of matrix2 is: [[-0.5     1.4375 -1.25  ]
 [ 1.     -1.875   1.5   ]
 [ 0.     -0.375   0.5   ]]


In [14]:
#trace of matrix
print("\nTrace of martix1 is:",matrix1.trace())
print("\nTrace of matrix2 is:",matrix2.trace())


Trace of martix1 is: [[15]]

Trace of matrix2 is: [[18]]


In [15]:
#standard deviation of matrix
print("\nStandard Deviation of martix1 is:",np.std(matrix1))
print("\nStandard Deviation of matrix2 is:",np.std(matrix2))


Standard Deviation of martix1 is: 2.581988897471611

Standard Deviation of matrix2 is: 2.006163342807532


In [16]:
#calculate Eigen Values and Eigen vectors
eigenvalue, eigenvector = np.linalg.eig(matrix1)
print("\nThe Eigen Values of matrix1 is:",eigenvalue)
print("\nThe Eigen Vector of matrix1 is:",eigenvector)


The Eigen Values of matrix1 is: [ 1.61168440e+01 -1.11684397e+00 -4.22209278e-16]

The Eigen Vector of matrix1 is: [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [17]:
#Calculate The Sigular Value Decomposition of matrix:
u, s, vh = np.linalg.svd(matrix1)
print("\nThe SVD of matrix1 is:")
print("\mThe value of u is:",u)
print("The value of sigma is:",s)
print("The value of V transpose is:",vh)


The SVD of matrix1 is:
\mThe value of u is: [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
The value of sigma is: [1.68481034e+01 1.06836951e+00 4.41842475e-16]
The value of V transpose is: [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


In [18]:
#converting matrix in the list form
print(matrix1)
matrix1.reshape(-1)

matrix([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [25]:
#converting two dimentional array to list form
y = array1.tolist()
print(y)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [34]:
#sorting of arrays 
print(array2.sort(axis=0))

None


In [35]:
#finding the gradient
np.gradient(array2)

[array([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])]